/* Don't EDIT, It's auto generated! */

var pattern_nv = new Array();

pattern_nv = {
	1: "pattern_lr_left_1_right_1_left_big",
	2: "pattern_lr_left_1_right_1_right_big",
	3: "pattern_lr_left_middle_right",
	4: "pattern_lr_left_1_right_2",
	5: "pattern_lr_left_2_right_1",
	6: "pattern_lr_left_2_right_2",
	7: "pattern_lr_left_1_right_many",
	8: "pattern_lr_left_many_right_1",
	9: "pattern_lr_left_many_right_many",
	11: "pattern_ud_up_1_down_1_up_big",
	12: "pattern_ud_up_1_down_1_down_big",
	13: "pattern_ud_up_middle_down",
	14: "pattern_ud_up_1_down_2",
	15: "pattern_ud_up_2_down_1",
	16: "pattern_ud_up_2_down_2",
	17: "pattern_ud_up_1_down_many",
	18: "pattern_ud_up_many_down_1",
	19: "pattern_ud_up_many_down_many",
	21: "pattern_single",
	31: "pattern_round_whole",
	32: "pattern_round_up",
	33: "pattern_round_down",
	34: "pattern_round_left",
	35: "pattern_round_right",
	36: "pattern_round_left_up",
	37: "pattern_round_left_down",
	38: "pattern_round_right_up",
	41: "pattern_pin",
	51: "pattern_",
}
