/* 横竖撇捺折 for 独体字 续笔 */
/* na can not be the the first stroke of a character */
var heng                            = 1; 
var ti                              = 2; 
var shu                             = 3; 
var pie                             = 4; 
var na                              = 5; 
var dian                            = 6; 
var zhe                             = 7; 
var hengzheshu                      = 8;  /* 口 */
var hengzhepie                      = 9;  /* 又 */
var henggou                         = 10;  /* 买 */
var shuzheheng                      = 11;  /* 山 */
var shugou                          = 12;  /* 求 */
var shuzheti                        = 13;  /* 长 */
var piezheheng                      = 14;  /* 厶 */
var piezhedian                      = 15;  /* 女 */
var wanshugou                       = 16;  /* 犹，家 */
var nagou                           = 17;  /* 代，戈 */
var hengzheshuzheheng               = 18;  /* 凹 */
var hengzheshuzheti                 = 19;  /* 说，言字旁 */
var hengzheshugou                   = 20;  /* 习 */
var hengzhenagou                    = 21;  /* 飞 */
var shuzhehengzheshu                = 22;  /* 鼎 */
var shuzhehengzhepie                = 23;  /* 专 */
var shuwanhenggou                   = 24;  /* 己，匕 */
var hengzheshuzhehengzheshu         = 25;  /* 凸 */
var hengzheshuzhehengzhepie         = 26;  /* 及 */
var hengzheshuwanhenggou            = 27;  /* 几，乙 */
var hengzhepiezhewanshugou          = 28;  /* 阳 */
var shuzhehengzheshugou             = 29;  /* 与，马 */
var hengzheshuzhehengzheshugou      = 30;  /* 乃，杨 */
var liaheng							= 31;  /* 日，俩横 */
